// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChi631qxLD3hLl4wwo0RJDHT817PcWmr8',
    appId: '1:349711920027:web:8d5c785ce57bc280d0cf3e',
    messagingSenderId: '349711920027',
    projectId: 'mitdemo-82202',
    authDomain: 'mitdemo-82202.firebaseapp.com',
    storageBucket: 'mitdemo-82202.firebasestorage.app',
    measurementId: 'G-MYMRC37TGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6hwsz_BWdy9MhX28R6JyryIX5bk-Ml0',
    appId: '1:349711920027:android:754a8215a07808a7d0cf3e',
    messagingSenderId: '349711920027',
    projectId: 'mitdemo-82202',
    storageBucket: 'mitdemo-82202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRcwE59-Piv68m0IxNofu8aUsJG-nsCKE',
    appId: '1:349711920027:ios:410448bbb8b4cbf1d0cf3e',
    messagingSenderId: '349711920027',
    projectId: 'mitdemo-82202',
    storageBucket: 'mitdemo-82202.firebasestorage.app',
    iosBundleId: 'com.example.lecture12firebaseDb',
  );
}
